# Generated by Django 6.0.5 on 2026-06-30 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='firms.lawfirm'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_client_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='clients.client'),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estateclient',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estate_profile', to='clients.client'),
        ),
        migrations.AddField(
            model_name='governmentclient',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='government_profile', to='clients.client'),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_profile', to='clients.client'),
        ),
        migrations.AddField(
            model_name='ngoclient',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_profile', to='clients.client'),
        ),
        migrations.AddField(
            model_name='partnershipclient',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_profile', to='clients.client'),
        ),
        migrations.AddField(
            model_name='trustclient',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_profile', to='clients.client'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_type'], name='clients_client__78316d_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['access_type'], name='clients_access__9aec7c_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['national_id'], name='clients_nationa_366fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['passport_number'], name='clients_passpor_3c81a6_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaddress',
            index=models.Index(fields=['client'], name='client_addr_client__47e105_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaddress',
            index=models.Index(fields=['address_type'], name='client_addr_address_e8aca7_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaddress',
            index=models.Index(fields=['country'], name='client_addr_country_746694_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['client', 'contact_type'], name='client_cont_client__7de7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['phone_number'], name='client_cont_phone_n_855196_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['email'], name='client_cont_email_c09782_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['client', 'document_type'], name='client_docu_client__d24a14_idx'),
        ),
        migrations.AddIndex(
            model_name='companyclient',
            index=models.Index(fields=['registration_number'], name='company_cli_registr_04460b_idx'),
        ),
        migrations.AddIndex(
            model_name='companyclient',
            index=models.Index(fields=['company_status'], name='company_cli_company_599c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='companyclient',
            index=models.Index(fields=['industry'], name='company_cli_industr_9cb0cf_idx'),
        ),
    ]
