# Generated by Django 6.0.5 on 2026-06-23 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyClient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='company_details', serialize=False, to='clients.client')),
                ('company_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'company_clients',
            },
        ),
        migrations.CreateModel(
            name='EstateClient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estate_details', serialize=False, to='clients.client')),
                ('estate_name', models.CharField(max_length=255)),
                ('executor_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estate_clients',
            },
        ),
        migrations.CreateModel(
            name='TrustClient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trust_details', serialize=False, to='clients.client')),
                ('trust_name', models.CharField(max_length=255)),
                ('trust_reference', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'trust_clients',
            },
        ),
    ]
