# Generated by Django 6.0.5 on 2026-06-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyclient',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='companyclient',
            name='postal_address',
        ),
        migrations.RemoveField(
            model_name='companyclient',
            name='primary_contact_email',
        ),
        migrations.RemoveField(
            model_name='companyclient',
            name='primary_contact_person',
        ),
        migrations.RemoveField(
            model_name='companyclient',
            name='primary_contact_phone',
        ),
        migrations.AlterModelTable(
            name='companyclient',
            table='company_clients',
        ),
    ]
