# Generated by Django 6.0.5 on 2026-06-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_companyclient_business_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientaddress',
            options={'verbose_name': 'Client Address', 'verbose_name_plural': 'Client Addresses'},
        ),
        migrations.AlterModelOptions(
            name='companyclient',
            options={'verbose_name': 'Company Client', 'verbose_name_plural': 'Company Clients'},
        ),
        migrations.AddField(
            model_name='companyclient',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='postal_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='primary_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='primary_contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='primary_contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='address_type',
            field=models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work'), ('POSTAL', 'Postal'), ('REGISTERED', 'Registered Office'), ('BILLING', 'Billing'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='clientaddress',
            index=models.Index(fields=['client'], name='client_addr_client__47e105_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaddress',
            index=models.Index(fields=['address_type'], name='client_addr_address_e8aca7_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaddress',
            index=models.Index(fields=['country'], name='client_addr_country_746694_idx'),
        ),
        migrations.AlterModelTable(
            name='clientaddress',
            table='client_addresses',
        ),
    ]
