# Generated by Django 6.0.5 on 2026-07-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershipclient',
            name='agreement_type',
            field=models.CharField(blank=True, choices=[('GENERAL_PARTNERSHIP', 'General Partnership Agreement'), ('LIMITED_PARTNERSHIP', 'Limited Partnership Agreement'), ('LIMITED_LIABILITY_PARTNERSHIP', 'Limited Liability Partnership Agreement'), ('JOINT_VENTURE', 'Joint Venture Agreement'), ('SILENT_PARTNERSHIP', 'Silent Partnership Agreement'), ('STRATEGIC_ALLIANCE', 'Strategic Alliance Agreement'), ('PROFIT_SHARING', 'Profit Sharing Agreement'), ('MEMORANDUM_OF_UNDERSTANDING', 'Memorandum of Understanding')], max_length=100, null=True),
        ),
    ]
