# Generated by Django 6.0.5 on 2026-06-23 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_companyclient_estateclient_trustclient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at']},
        ),
    ]
