# Generated by Django 6.0.5 on 2026-06-24 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_clientaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='address_type',
            field=models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work'), ('OFFICE', 'Office'), ('POSTAL', 'Postal'), ('REGISTERED', 'Registered Office'), ('BILLING', 'Billing'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.CreateModel(
            name='PartnershipClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_pin', models.CharField(blank=True, max_length=100, null=True)),
                ('formation_date', models.DateField(blank=True, null=True)),
                ('partner_count', models.PositiveIntegerField(default=0)),
                ('agreement_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_profile', to='clients.client')),
            ],
            options={
                'db_table': 'partnership_clients',
            },
        ),
    ]
