# Generated by Django 6.0.5 on 2026-07-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_partnershipclient_agreement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
