# Generated by Django 6.0.5 on 2026-07-04 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_create_lawyer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staff',
            name='unique_staff_number_per_firm',
        ),
        migrations.RemoveConstraint(
            model_name='staff',
            name='unique_employee_number_per_firm',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
