# Generated by Django 6.0.5 on 2026-07-06 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0002_alter_lawfirmmember_role'),
        ('staff', '0003_remove_staff_unique_staff_number_per_firm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_number', models.CharField(max_length=30)),
                ('employee_number', models.CharField(blank=True, max_length=30, null=True)),
                ('firm_role', models.CharField(choices=[('LAWYER', 'Lawyer'), ('SECRETARY', 'Secretary'), ('IT', 'IT Support'), ('ACCOUNTANT', 'Accountant'), ('HR', 'Human Resource'), ('OFFICIAL_CLIENT', 'Official Client')], default='SECRETARY', editable=False, max_length=40)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(default='Secretary', max_length=100)),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('office_location', models.CharField(blank=True, max_length=255, null=True)),
                ('can_prepare_documents', models.BooleanField(default=True)),
                ('can_schedule_appointments', models.BooleanField(default=True)),
                ('can_manage_client_intake', models.BooleanField(default=True)),
                ('can_receive_documents', models.BooleanField(default=True)),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('PART_TIME', 'Part Time'), ('INTERN', 'Intern'), ('CONSULTANT', 'Consultant'), ('TEMPORARY', 'Temporary')], default='PERMANENT', max_length=20)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROBATION', 'Probation'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20)),
                ('date_hired', models.DateField()),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('date_terminated', models.DateField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_lawyers', models.ManyToManyField(blank=True, related_name='assigned_secretaries', to='staff.lawyer')),
                ('law_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretaries', to='firm.lawfirm')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretaries', to='staff.lawyer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secretary_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secretary',
                'verbose_name_plural': 'Secretaries',
                'db_table': 'staff_secretaries',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='SecretaryPermissionGrant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('MANAGE_CLIENTS', 'Manage Clients'), ('MANAGE_CASES', 'Manage Cases'), ('MANAGE_DOCUMENTS', 'Manage Documents'), ('MANAGE_CALENDAR', 'Manage Calendar'), ('MANAGE_TASKS', 'Manage Tasks'), ('SEND_COMMUNICATIONS', 'Send Communications'), ('VIEW_REPORTS', 'View Reports'), ('MANAGE_BILLING', 'Manage Billing')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_secretary_permissions', to=settings.AUTH_USER_MODEL)),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='staff.secretary')),
            ],
            options={
                'db_table': 'staff_secretary_permissions',
            },
        ),
        migrations.AddConstraint(
            model_name='secretary',
            constraint=models.UniqueConstraint(fields=('law_firm', 'staff_number'), name='unique_secretary_staff_number_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='secretary',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_number__isnull', False)), fields=('law_firm', 'employee_number'), name='unique_secretary_employee_number_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='secretarypermissiongrant',
            constraint=models.UniqueConstraint(fields=('secretary', 'code'), name='unique_secretary_permission'),
        ),
    ]
