# Generated by Django 6.0.5 on 2026-07-07 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_hr_accountant_hrpermissiongrant_it_itpermissiongrant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerPermissionGrant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('MANAGE_ASSIGNED_CASES', 'Manage Assigned Cases'), ('CREATE_CASES', 'Create Cases'), ('MANAGE_CASE_DOCUMENTS', 'Manage Case Documents'), ('SCHEDULE_HEARINGS', 'Schedule Hearings'), ('MANAGE_CLIENT_COMMUNICATIONS', 'Manage Client Communications'), ('USE_LEGAL_RESEARCH', 'Use Legal Research'), ('USE_AI_TOOLS', 'Use AI Tools'), ('APPROVE_DOCUMENTS', 'Approve Documents'), ('VIEW_BILLING', 'View Billing')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_lawyer_permissions', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='staff.lawyer')),
            ],
            options={
                'db_table': 'staff_lawyer_permissions',
                'constraints': [models.UniqueConstraint(fields=('lawyer', 'code'), name='unique_lawyer_permission')],
            },
        ),
    ]
