# Generated by Django 6.0.5 on 2026-07-08 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0003_branch_branch_leader_department_head'),
        ('staff', '0006_lawyerpermissiongrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountant',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountants', to='firm.branch'),
        ),
        migrations.AddField(
            model_name='accountant',
            name='department_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountants', to='firm.department'),
        ),
        migrations.AddField(
            model_name='hr',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_staff', to='firm.branch'),
        ),
        migrations.AddField(
            model_name='hr',
            name='department_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_staff', to='firm.department'),
        ),
        migrations.AddField(
            model_name='it',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_staff', to='firm.branch'),
        ),
        migrations.AddField(
            model_name='it',
            name='department_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_staff', to='firm.department'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawyers', to='firm.branch'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='department_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawyers', to='firm.department'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretaries', to='firm.branch'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='department_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretaries', to='firm.department'),
        ),
    ]
