# Generated by Django 6.0.5 on 2026-07-07 18:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_clientcontact_national_id_number'),
        ('firm', '0002_alter_lawfirmmember_role'),
        ('staff', '0006_lawyerpermissiongrant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('case_type', models.CharField(choices=[('CIVIL', 'Civil'), ('CRIMINAL', 'Criminal'), ('FAMILY', 'Family'), ('LAND', 'Land'), ('EMPLOYMENT', 'Employment'), ('COMMERCIAL', 'Commercial'), ('SUCCESSION', 'Succession'), ('CONSTITUTIONAL', 'Constitutional'), ('TAX', 'Tax'), ('IMMIGRATION', 'Immigration')], max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('CLOSED', 'Closed'), ('DISMISSED', 'Dismissed'), ('JUDGMENT_DELIVERED', 'Judgment Delivered'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=40)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('court_type', models.CharField(choices=[('MAGISTRATE', 'Magistrate Court'), ('HIGH_COURT', 'High Court'), ('COURT_OF_APPEAL', 'Court of Appeal'), ('SUPREME_COURT', 'Supreme Court'), ('ENVIRONMENT_LAND', 'Environment and Land Court'), ('EMPLOYMENT_LABOUR', 'Employment and Labour Court'), ('SMALL_CLAIMS', 'Small Claims Court'), ('KADHI', 'Kadhi Court'), ('TRIBUNAL', 'Tribunal'), ('OTHER', 'Other')], max_length=40)),
                ('court_name', models.CharField(blank=True, default='', max_length=255)),
                ('court_location', models.CharField(blank=True, default='', max_length=255)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('plaintiff', models.CharField(blank=True, default='', max_length=255)),
                ('defendant', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='staff.lawyer')),
                ('assigned_secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='staff.secretary')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='firm.lawfirm')),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_activities', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cases.case')),
            ],
            options={
                'db_table': 'case_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTimeline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_timeline_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'case_timeline',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['firm', 'status'], name='cases_firm_id_ba54de_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['firm', 'priority'], name='cases_firm_id_cdaf61_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['firm', 'case_type'], name='cases_firm_id_66e436_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['client'], name='cases_client__260b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assigned_lawyer'], name='cases_assigne_e69e63_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assigned_secretary'], name='cases_assigne_61e740_idx'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('firm', 'case_number'), name='unique_case_number_per_firm'),
        ),
    ]
