import {
  Banknote,
  Bell,
  CalendarDays,
  ClipboardList,
  FileText,
  LayoutDashboard,
  Lock,
  MonitorCog,
  ReceiptText,
  ShieldCheck,
  User,
  UsersRound,
} from 'lucide-react';

export const staffRoleConfigs = {
  accountant: {
    firmRole: 'ACCOUNTANT',
    label: 'Accountant',
    title: 'Accountant Dashboard',
    basePath: '/accountant',
    apiBase: '/staff/accountant',
    badge: 'Finance',
    description:
      'Manage billing, payments, financial records, and accounting operations for the firm.',
    statusTitle: 'Finance Workspace Active',
    primaryIcon: Banknote,
    navLinks: [
      { name: 'Dashboard', path: '/accountant/dashboard', icon: LayoutDashboard, end: true },
      { name: 'Billing', path: '/accountant/billing', icon: ReceiptText },
      { name: 'Tasks', path: '/accountant/tasks', icon: ClipboardList },
      { name: 'Documents', path: '/accountant/documents', icon: FileText },
      { name: 'Calendar', path: '/accountant/calendar', icon: CalendarDays },
      { name: 'Notifications', path: '/accountant/notifications', icon: Bell },
      { name: 'Profile', path: '/accountant/profile', icon: User },
      { name: 'Security', path: '/accountant/security', icon: Lock },
    ],
    tiles: [
      { title: 'Billing', subtitle: 'Invoices, payments, and client billing', icon: ReceiptText, variant: 'billing', path: '/accountant/billing', size: 'large' },
      { title: 'Tasks', subtitle: 'Finance work requiring attention', icon: ClipboardList, variant: 'tasks', path: '/accountant/tasks', size: 'wide' },
      { title: 'Documents', subtitle: 'Financial documents and records', icon: FileText, variant: 'documents', path: '/accountant/documents', size: 'wide' },
      { title: 'Calendar', subtitle: 'Deadlines, payment dates, and schedules', icon: CalendarDays, variant: 'calendar', path: '/accountant/calendar', size: 'wide' },
      { title: 'Notifications', subtitle: 'Alerts from finance workflows', icon: Bell, variant: 'notifications', path: '/accountant/notifications', size: 'wide' },
      { title: 'Profile', subtitle: 'Your role, permissions, and work contacts', icon: User, variant: 'staff', path: '/accountant/profile', size: 'wide' },
    ],
  },
  hr: {
    firmRole: 'HR',
    label: 'HR',
    title: 'HR Dashboard',
    basePath: '/hr',
    apiBase: '/staff/hr',
    badge: 'Human Resource',
    description:
      'Manage staff records, recruitment workflows, leave, and internal HR operations.',
    statusTitle: 'HR Workspace Active',
    primaryIcon: UsersRound,
    navLinks: [
      { name: 'Dashboard', path: '/hr/dashboard', icon: LayoutDashboard, end: true },
      { name: 'Staff Records', path: '/hr/staff-records', icon: UsersRound },
      { name: 'Tasks', path: '/hr/tasks', icon: ClipboardList },
      { name: 'Documents', path: '/hr/documents', icon: FileText },
      { name: 'Calendar', path: '/hr/calendar', icon: CalendarDays },
      { name: 'Notifications', path: '/hr/notifications', icon: Bell },
      { name: 'Profile', path: '/hr/profile', icon: User },
      { name: 'Security', path: '/hr/security', icon: Lock },
    ],
    tiles: [
      { title: 'Staff Records', subtitle: 'Employee files and HR records', icon: UsersRound, variant: 'staff', path: '/hr/staff-records', size: 'large' },
      { title: 'Tasks', subtitle: 'HR assignments and follow-ups', icon: ClipboardList, variant: 'tasks', path: '/hr/tasks', size: 'wide' },
      { title: 'Documents', subtitle: 'Contracts, notices, and HR files', icon: FileText, variant: 'documents', path: '/hr/documents', size: 'wide' },
      { title: 'Calendar', subtitle: 'Leave dates, reviews, and schedules', icon: CalendarDays, variant: 'calendar', path: '/hr/calendar', size: 'wide' },
      { title: 'Notifications', subtitle: 'Staff and policy updates', icon: Bell, variant: 'notifications', path: '/hr/notifications', size: 'wide' },
      { title: 'Profile', subtitle: 'Your role, permissions, and contacts', icon: User, variant: 'clients', path: '/hr/profile', size: 'wide' },
    ],
  },
  it: {
    firmRole: 'IT',
    label: 'IT',
    title: 'IT Dashboard',
    basePath: '/it',
    apiBase: '/staff/it',
    badge: 'IT Support',
    description:
      'Monitor systems, handle support work, security checks, and technical operations.',
    statusTitle: 'IT Workspace Active',
    primaryIcon: MonitorCog,
    navLinks: [
      { name: 'Dashboard', path: '/it/dashboard', icon: LayoutDashboard, end: true },
      { name: 'Systems', path: '/it/systems', icon: MonitorCog },
      { name: 'Tasks', path: '/it/tasks', icon: ClipboardList },
      { name: 'Documents', path: '/it/documents', icon: FileText },
      { name: 'Calendar', path: '/it/calendar', icon: CalendarDays },
      { name: 'Notifications', path: '/it/notifications', icon: Bell },
      { name: 'Profile', path: '/it/profile', icon: User },
      { name: 'Security', path: '/it/security', icon: ShieldCheck },
    ],
    tiles: [
      { title: 'Systems', subtitle: 'System operations and support checks', icon: MonitorCog, variant: 'settings', path: '/it/systems', size: 'large' },
      { title: 'Tasks', subtitle: 'Technical work requiring action', icon: ClipboardList, variant: 'tasks', path: '/it/tasks', size: 'wide' },
      { title: 'Documents', subtitle: 'Technical guides and support records', icon: FileText, variant: 'documents', path: '/it/documents', size: 'wide' },
      { title: 'Calendar', subtitle: 'Maintenance windows and schedules', icon: CalendarDays, variant: 'calendar', path: '/it/calendar', size: 'wide' },
      { title: 'Notifications', subtitle: 'Security and system alerts', icon: Bell, variant: 'notifications', path: '/it/notifications', size: 'wide' },
      { title: 'Profile', subtitle: 'Your role, permissions, and contacts', icon: User, variant: 'staff', path: '/it/profile', size: 'wide' },
    ],
  },
};

export const getStaffRoleConfig = (roleKey) => staffRoleConfigs[roleKey];
