# Generated by Django 6.0.5 on 2026-07-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawfirmmember',
            name='role',
            field=models.CharField(choices=[('LAWYER', 'Lawyer'), ('SECRETARY', 'Secretary'), ('IT', 'IT Support'), ('ACCOUNTANT', 'Accountant'), ('HR', 'Human Resource'), ('OFFICIAL_CLIENT', 'Official Client')], max_length=30),
        ),
    ]
