# Generated by Django 6.0.5 on 2026-07-08 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0002_alter_lawfirmmember_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_leader',
            field=models.ForeignKey(blank=True, help_text='Staff member responsible for this branch. Defaults to the firm owner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Staff member responsible for this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
