# Generated by Django 6.0.5 on 2026-06-30 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'law_firms',
            },
        ),
        migrations.CreateModel(
            name='LawFirmMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('MANAGING_PARTNER', 'Managing Partner'), ('SENIOR_PARTNER', 'Senior Partner'), ('PARTNER', 'Partner'), ('ASSOCIATE', 'Associate'), ('SENIOR_ASSOCIATE', 'Senior Associate'), ('PUPIL', 'Pupil'), ('LEGAL_INTERN', 'Legal Intern'), ('SECRETARY', 'Secretary'), ('PARALEGAL', 'Paralegal'), ('LEGAL_CLERK', 'Legal Clerk'), ('ACCOUNTANT', 'Accountant'), ('HR', 'Human Resource'), ('IT', 'IT Support'), ('OFFICE_ADMINISTRATOR', 'Office Administrator'), ('OFFICE_ASSISTANT', 'Office Assistant'), ('RECEPTIONIST', 'Receptionist'), ('MESSENGER', 'Messenger')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'firm_members',
                'ordering': ['-created_at'],
            },
        ),
    ]
