# Generated by Django 6.0.5 on 2026-06-29 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lawfirm',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_firm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawfirmmember',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_firm_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawfirmmember',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='firms.lawfirm'),
        ),
        migrations.AddField(
            model_name='lawfirmmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='lawfirmmember',
            unique_together={('firm', 'user')},
        ),
    ]
