# Generated by Django 6.0.5 on 2026-06-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawfirmmember',
            name='role',
            field=models.CharField(choices=[('MANAGING_PARTNER', 'Managing Partner'), ('SENIOR_PARTNER', 'Senior Partner'), ('PARTNER', 'Partner'), ('ASSOCIATE', 'Associate'), ('SENIOR_ASSOCIATE', 'Senior Associate'), ('PUPIL', 'Pupil'), ('LEGAL_INTERN', 'Legal Intern'), ('SECRETARY', 'Secretary'), ('PARALEGAL', 'Paralegal'), ('LEGAL_CLERK', 'Legal Clerk'), ('ACCOUNTANT', 'Accountant'), ('HR', 'Human Resource'), ('IT', 'IT Support'), ('OFFICE_ADMINISTRATOR', 'Office Administrator'), ('OFFICE_ASSISTANT', 'Office Assistant'), ('RECEPTIONIST', 'Receptionist'), ('MESSENGER', 'Messenger')], max_length=30),
        ),
    ]
