# Generated by Django 6.0.5 on 2026-06-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('CLIENT', 'Client'), ('PORTAL_CLIENT', 'Portal Client')], default='PORTAL_CLIENT', max_length=30),
        ),
    ]
