# Generated by Django 6.0.5 on 2026-06-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firm_role',
        ),
    ]
